development: &default
  session_secret: 'b76d2284dbe546ea6530f98d4580e077ae985f38fc749ca3a31f614cc5fa2bcf'
  site_url: 'http://localhost:3000'
  site_title: 'ONECOIN.IM'
  site_motto: '维卡币操盘手:追踪最新动态，分享投资技巧，提供操盘工具'
  site_description: '维卡币（中国）官方网站，人工翻译最新通告，提供专业投资资讯和投资工具'
  blog_search_ping: false
  google_cse: '1234567890:0123'
  weibo_api_key: '1234567890'
  weibo_api_secret: '1234567890'
  weibo_redirect_uri: 'http://onecoin.im/weibo_callback'
  weibo_uid: '12345678'
  weibo_uid_verifier: '87654321'

test: 
  <<: *default

production:
  <<: *default
  site_url: 'http://onecoin.im'
  blog_search_ping: true
